name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: publish releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Golang
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.4'
      - name: Build And Download Stickers
        run: chmod +x ./exec.sh && ./exec.sh
      - name: Use Zip
        uses: montudor/action-zip@v1
      - name: Package Stickers
        run: chmod +x ./package.sh && ./package.sh
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: package/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}